version: "3.8"
services:
  web:
    build: .
    depends_on: 
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    deploy:    
      replicas: 3
  redis:
    image: "redis:alpine"
    deploy:
      replicas: 2
