version: '3'

services:
  dbagent:
    image: ivlevinsky/dbagent-centos:4.5.15.1486
    #container_name: dbagent
    networks:
      - lab
      - database
    environment:
      - APPDYNAMICS_CONTROLLER_HOST_NAME=controller
      - APPDYNAMICS_CONTROLLER_PORT=8090
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=0d28b866-767d-452c-88c7-4fa39418bd7c
    restart: always
    depends_on:
      - maria_db

  maria_db:
    image: mariadb:latest
    #container_name: mariadb
    networks:
      - database
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    restart: always

networks:
  lab:
    name: lab
  database:
    name: database
