version: '3'

services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    networks:
      - database
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.local
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

networks:
  database:
    name: database
